- name: Import the Microsoft repository key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add repository (RedHat)
  yum_repository:
    name: azure_cli
    description: Galaxy Packages for Enterprise Linux $releasever - $basearch
    baseurl: https://packages.microsoft.com/yumrepos/azure-cli
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc


- name: install azure-cli
  package:
    name:
      - azure-cli

- name: Add microsoft prod repo
  yum_repository:
    name: packages-microsoft-com-prod
    description: packages-microsoft-com-prod
    baseurl: https://packages.microsoft.com/rhel/8/prod
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: install blobfuse
  package:
    name:
      - blob-fuse
